before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: binary
    main: ./cmd/ansible-operator/
    binary: ansible-operator
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
    - linux
    goarch:
    - s390x
dockers:
- image_templates:
    - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-s390x"
  dockerfile: images/ansible-operator/Dockerfile
  goos: linux
  goarch: s390x
  use: buildx
  build_flag_templates:
    - "--platform=linux/s390x"
  extra_files:
    - "images/ansible-operator/Pipfile"
    - "images/ansible-operator/Pipfile.lock"
#docker_manifests:
#- name_template: "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}"
#  image_templates:
#    - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-amd64"
#    - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-arm64"
#    - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-ppc64le"
#    - "{{ .Env.IMAGE_REPO }}:{{ .Env.IMAGE_TAG }}-s390x"
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
changelog:
  use: github-native
  skip: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
